[package]
name = "read-from"
version = "0.1.0"
authors = ["Sam Westerman <sam@sampersand.me>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "Supplies the ReadFrom and WriteTo traits."

[dependencies]
